application: leesah-piki
version: development
runtime: python
api_version: 1

handlers:
- url: /know
  script: know.py
  login: required

- url: /_ah/login_required__
  script: login.py

- url: /welcome
  script: welcome.py

- url: /predict
  script: predict.py
  
- url: /test
  script: test
  
- url: /.*
  script: main.py
  
  