application: leesah-piki
version: development
runtime: python
api_version: 1

handlers:
- url: /know
  script: know.py
  login: required

- url: /predict
  script: predict.py
  
- url: /_ah/login_required
  script: main.py

- url: /.*
  script: main.py
  
  